### ISSUE TITLE
Monterey issue

### ISSUE THREAD

**Issue by christianpape** [Yohan460/Programmatic-OD-Python-Binding#1]
This script is awesome and I used it for Big Sur, but unfortunately 
it doesn't seem to work for Monterey.

**Comment by MacTroy** [comment]
I've got it working with Monterey, but from 12.3 on you need to BYOP, because Apple yoinked Python out of the OS. See my pull request "Monterey and managed_python" from today.

**Comment by Yohan460** [comment]
Thank you @MacTroy! Merged!
